apiVersion: ai-manager.watson-aiops.ibm.com/v1beta1
kind: AIManager
metadata:
  name: aimanager
  namespace: aiops21
spec:
  existingPullSecret:
    name: cp.stg.icr.io
  flink:
    storage:
      enabled: true
      storageClassName: ''
      storageSize: 1Gi
    taskmanager:
      replicas: 1
      taskmanagerSlots: 12
  size: small
  license:
    accept: true
  zen:
    storage:
      storageClassName: ''
  kafka:
    autoTopicCreation: true
    storage:
      enabled: true
      storageClassName: ''
      storageSize: 20Gi
  aimanagerValues:
    postgres:
      keeper:
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      livenessProbe:
        failureThreshold: 5
        initialDelaySeconds: 300
        periodSeconds: 15
        successThreshold: 1
        timeoutSeconds: 15
      readinessProbe:
        failureThreshold: 5
        initialDelaySeconds: 300
        periodSeconds: 15
        successThreshold: 1
        timeoutSeconds: 15
      sentinel:
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
  repo: ''
  version: 2.1.0
  minio:
    storage:
      enabled: true
      storageClassName: ''
      storageSize: 100Gi
  postgres:
    storage:
      enabled: true
      storageClassName: ''
      storageSize: 20Gi
  storage:
    enabled: true
    storageClassName: ibmc-file-gold-gid
  elasticsearch:
    storage:
      enabled: true
      storageClassName: ''
      storageSize: 100Gi
  modelTrain:
    maxLearners: 10
    pollInterval: 60
    sizeLimit: 1000
